language: ruby
rvm:
 - 2.5.0

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

cache:
  bundler: true
  directories:
    - vendor/cache
