# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5d3b8bc0614b56978056d1ca9bc8893d5939f682d2b815e97cf676b564d0a141429a450c403bc4d67eb181e1e1495f5d999fb313190f2f2374474811655f6227

test:
  secret_key_base: 8c6d31586732cd23402244fb3946ad1c35bdbf957c55bc9300a7d02936df1c7c24f7c177aeada606fa998794aff54d9e41cf90bdc1d685bfbc039cf443037b10

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
